// ═══════════════════════════════════════════════════════
//  REISEDATEN — hier alle Infos zur Reise pflegen
// ═══════════════════════════════════════════════════════

const REISE = {
  titel:       "Bretagne & Normandie",
  zeitraum:    "13. Mai – 30. Mai 2026",
  start:       new Date("2026-05-13"),
  end:         new Date("2026-05-30"),
  tagline:     "13. Mai – 30. Mai · Tesla · 🐾",
  stats: [
    { val: "4",    label: "Etappen"    },
    { val: "17",   label: "Nächte"     },
    { val: "1710", label: "km"         },
    { val: "4 ★",  label: "Unterkünfte"},
  ],
  mapsLink:    "https://maps.app.goo.gl/ZXjmhrsYRp2C3i91A",
  masterDoc:   "https://docs.google.com/document/d/1Fqlifn0YZue2BEvFc9A-dgzlf0xBnli1DHgJgZsDlDA",
  docPubUrl:   "https://docs.google.com/document/d/e/2PACX-1vSnru4coTD1Bne3fYE_MNXOTI5VSuRkugAmgHdVSBx2NLeZk7bYNR0qB5Y45NoSKtZANpyxlP6Cp1VC/pub",
  // Nach Apps Script Deploy: URL hier eintragen
  appsScriptUrl: "https://script.google.com/macros/s/AKfycbzgU2HUnnri0eJVafcjXggv2dCvQc87QQGHjGhf-y6aSQbuEXG1q01Rfd8omNEM8w-A/exec",
  alert:       "⚠️ Klippen-Abbruchgefahr · Criel-sur-Mer: Leinenpflicht für Hund.",
  logistik: [
    {
      icon: "🐾", title: "Hund",
      text: "Pfotenwachs für Kiesel und Granit einpacken.\n\nVor dem 1. Juni Strände oft noch frei zugänglich.",
      warn: false
    },
    {
      icon: "⚠️", title: "Klippen · Criel-sur-Mer",
      text: "Höchste Kreidefelsen Europas — Abbruchgefahr. Leinenpflicht für Hund. Rand meiden.",
      warn: true
    },
    {
      icon: "🌊", title: "Highlights",
      text: "Pointe de Pen-Hir · Schroffste Klippen Frankreichs\nCap de Carteret · Panorama zu den Kanalinseln\nPlage de la Vieille Église · Riesig bei Ebbe\nAlabasterküste · Höchste Kreidefelsen Europas",
      warn: false
    },
  ]
};

const ETAPPEN = [
  {
    num:    "01",
    color:  "#78aba0",
    name:   "Valenciennes",
    region: "Stopover · Nordfrankreich",
    dates:  "13.05. – 14.05.",
    km:     "460 km",
    fahrtzeit: "5,5 Std.",
    naechte:   "1 Nacht",
    start:  new Date("2026-05-13"),
    end:    new Date("2026-05-14"),
    unterkunft:     "Première Classe Valenciennes Sud",
    adresse:        "ZI n°2 – B900 Rue Louis-Dacquin, 59220 Rouvignies",
    checkin:        "13. Mai ab 14:00",
    checkout:       "14. Mai bis 11:00",
    confirmation:   null,
    buchungLink:    "https://secure.booking.com/app_link/myreservations.de.html?stid=325542&bn=6526897918&aid=332731",
    buchungPlattform: "Booking.com",
    highlight: "Strategischer Stopover direkt an der A2. Check-in rund um die Uhr per Automat.",
    chips: [
      { t: "🅿️ Gratis Parkplatz", s: true  },
      { t: "📶 WLAN",              s: true  },
      { t: "🔄 Check-in 24/7",    s: true  },
      { t: "🍳 Frühstück 6€",     s: false },
    ],
    lat: 50.3580, lng: 3.5239,
    mapsQ: "Première+Classe+Valenciennes+Sud+59220",
  },
  {
    num:    "02",
    color:  "#c9a568",
    name:   "Cotentin",
    region: "Barneville-Carteret · Normandie",
    dates:  "14.05. – 19.05.",
    km:     "420 km",
    fahrtzeit: "4,5 Std.",
    naechte:   "5 Nächte",
    start:  new Date("2026-05-14"),
    end:    new Date("2026-05-19"),
    unterkunft:     "Le Skiff · Villa Plein Vent",
    adresse:        "Rue des Fauvettes 13, 50270 Barneville-Carteret",
    checkin:        "14. Mai ab 17:30",
    checkout:       "19. Mai",
    confirmation:   "5461895880",
    buchungLink:    "https://secure.booking.com/app_link/myreservations.de.html?stid=325542&bn=5461895880&aid=332731",
    buchungPlattform: "Booking.com",
    highlight: "Beachfront-Villa mit Panoramablick auf die Kanalinseln. 4-Sterne Ferienhaus.",
    chips: [
      { t: "🌊 250 m zum Strand",   s: true },
      { t: "🛁 Jacuzzi",             s: true },
      { t: "🚲 Fahrräder inkl.",     s: true },
      { t: "⭐ 9.7 Booking", star: true      },
    ],
    lat: 49.3755, lng: -1.7765,
    mapsQ: "Rue+des+Fauvettes+13+50270+Barneville-Carteret",
  },
  {
    num:    "03",
    color:  "#9888c0",
    name:   "Crozon",
    region: "Camaret-sur-Mer · Bretagne",
    dates:  "19.05. – 25.05.",
    km:     "330 km",
    fahrtzeit: "3,5 Std.",
    naechte:   "6 Nächte",
    start:  new Date("2026-05-19"),
    end:    new Date("2026-05-25"),
    unterkunft:     "Haus Lambézen",
    adresse:        "Lambézen, 29570 Camaret-sur-Mer, Bretagne",
    checkin:        "19. Mai",
    checkout:       "25. Mai",
    confirmation:   "HA-BWZJ2K",
    buchungLink:    "https://www.fewo-direkt.de/de-de/trips/egti-JQF-XO4-CZTX/details/OTAyMDI0NjA4OTc4MztlZzpwcm9wZXJ0eTp2MjphM2E5NDIxMDE1MWZjYWIwNTFkNTJiOTQ1MjNmNzM1NA",
    buchungPlattform: "FeWo-Direkt",
    highlight: "Kleines renoviertes Steinhaus, ruhig gelegen. Pointe de Pen-Hir nur 7 Minuten entfernt.",
    chips: [
      { t: "🌊 500 m zum Meer",          s: true },
      { t: "🧺 Waschmaschine",            s: true },
      { t: "🥾 Wanderwege ab Haustür",    s: true },
      { t: "⭐ 9.4 Außergewöhnlich", star: true   },
    ],
    lat: 48.2776, lng: -4.5887,
    mapsQ: "Lambézen+29570+Camaret-sur-Mer",
  },
  {
    num:    "04",
    color:  "#bf7068",
    name:   "Alabasterküste",
    region: "Criel-sur-Mer · Normandie",
    dates:  "25.05. – 30.05.",
    km:     "500 km",
    fahrtzeit: "6 Std.",
    naechte:   "5 Nächte",
    start:  new Date("2026-05-25"),
    end:    new Date("2026-05-30"),
    unterkunft:     "Horizon d'Opale",
    adresse:        "2 Impasse des Cygnes, 76910 Criel-sur-Mer (3. OG · Aufzug)",
    checkin:        "25. Mai · Schlüsselbox",
    checkout:       "30. Mai",
    confirmation:   null,
    buchungLink:    "https://www.airbnb.de/trips/v1/reservation-details/ro/RESERVATION2_CHECKIN/HMXXPYRX39",
    buchungPlattform: "Airbnb",
    highlight: "180° Meerblick aus dem 3. Stock. Natura-2000-Gebiet mit Schwänen direkt vor der Tür.",
    chips: [
      { t: "🌊 Direkt am Strand",        s: true },
      { t: "180° Meerblick",             s: true },
      { t: "🅿️ Parkplatz B33",           s: true },
      { t: "⭐ 4.88 Gäste-Favorit", star: true   },
    ],
    lat: 50.0197, lng: 1.3098,
    mapsQ: "2+Impasse+des+Cygnes+76910+Criel-sur-Mer",
  },
];
