// ── CONFIGURATION ────────────────────────────────────────────────────────────
const CONFIG = {
  anthropicKey:  'ANTHROPIC_KEY_HERE',
  workerUrl:     'https://muddy-hall-ead6.philipp-51c.workers.dev/',
  appsScriptUrl: 'https://script.google.com/macros/s/AKfycbzVuZsw06w4NejYYQudXUbRUpocXX1iHKIzubvA5ppTSVOtZQS9vyhIgsi6qO6yW2k2/exec',
  mapsApiKey:    'AIzaSyAgh-3kD60VcglLsSEJ6lWMfUnDkj-BukA',
  mapsListUrl:   'https://maps.app.goo.gl/ZXjmhrsYRp2C3i91A',
  masterDocUrl:  'https://docs.google.com/document/d/1aLtGI3wMpkX4OxcORb7dbItrf8aCgRsmlpWhMG2JppM',
  docPubUrl:     'https://docs.google.com/document/d/e/2PACX-1vSnru4coTD1Bne3fYE_MNXOTI5VSuRkugAmgHdVSBx2NLeZk7bYNR0qB5Y45NoSKtZANpyxlP6Cp1VC/pub',
};

// ── TRIP DATA ─────────────────────────────────────────────────────────────────
const TRIP = {
  title:    'Bretagne & Normandie',
  year:     '2026',
  start:    new Date('2026-05-13'),
  end:      new Date('2026-05-30'),
  tagline:  'Tesla · 🐾 · 1710 km',
};

const ETAPPEN = [
  {
    id: 1,
    color: '#00e5ff',
    name: 'Valenciennes',
    region: 'Nordfrankreich',
    dates: '13.–14. Mai',
    km: '460',
    dauer: '5,5 Std.',
    naechte: 1,
    start: new Date('2026-05-13'),
    end:   new Date('2026-05-14'),
    unterkunft: 'Première Classe Valenciennes Sud',
    adresse: 'Rue Louis-Dacquin, 59220 Rouvignies',
    checkin: '13. Mai ab 14:00',
    checkout: '14. Mai bis 11:00',
    buchungNr: null,
    buchungUrl: 'https://secure.booking.com/app_link/myreservations.de.html?stid=325542&bn=6526897918&aid=332731',
    buchungPlattform: 'Booking.com',
    info: 'Stopover an der A2. Check-in 24/7 per Automat. Akku-Check für Weiterfahrt.',
    lat: 50.3580, lng: 3.5239,
    navUrl: 'https://maps.google.com/maps?daddr=50.3580,3.5239&directionsmode=driving',
  },
  {
    id: 2,
    color: '#ffe066',
    name: 'Cotentin',
    region: 'Barneville-Carteret · Normandie',
    dates: '14.–19. Mai',
    km: '420',
    dauer: '4,5 Std.',
    naechte: 5,
    start: new Date('2026-05-14'),
    end:   new Date('2026-05-19'),
    unterkunft: 'Le Skiff · Villa Plein Vent',
    adresse: 'Rue des Fauvettes 13, 50270 Barneville-Carteret',
    checkin: '14. Mai ab 17:30',
    checkout: '19. Mai',
    buchungNr: '5461895880',
    buchungUrl: 'https://secure.booking.com/app_link/myreservations.de.html?stid=325542&bn=5461895880&aid=332731',
    buchungPlattform: 'Booking.com',
    info: '250 m zum Strand. Jacuzzi. Fahrräder inklusive. Panorama auf Kanalinseln. ⭐ 9.7',
    lat: 49.3755, lng: -1.7765,
    navUrl: 'https://maps.google.com/maps?daddr=49.3755,-1.7765&directionsmode=driving',
  },
  {
    id: 3,
    color: '#b39ddb',
    name: 'Crozon',
    region: 'Camaret-sur-Mer · Bretagne',
    dates: '19.–25. Mai',
    km: '330',
    dauer: '3,5 Std.',
    naechte: 6,
    start: new Date('2026-05-19'),
    end:   new Date('2026-05-25'),
    unterkunft: 'Haus Lambézen',
    adresse: 'Lambézen, 29570 Camaret-sur-Mer',
    checkin: '19. Mai',
    checkout: '25. Mai',
    buchungNr: 'HA-BWZJ2K',
    buchungUrl: 'https://www.fewo-direkt.de/de-de/trips/egti-JQF-XO4-CZTX/details/OTAyMDI0NjA4OTc4MztlZzpwcm9wZXJ0eTp2MjphM2E5NDIxMDE1MWZjYWIwNTFkNTJiOTQ1MjNmNzM1NA',
    buchungPlattform: 'FeWo-Direkt',
    info: '500 m zum Meer. Steinhaus, ruhig. Pointe de Pen-Hir 7 Min. Wanderwege ab Haustür. ⭐ 9.4',
    lat: 48.2776, lng: -4.5887,
    navUrl: 'https://maps.google.com/maps?daddr=48.2776,-4.5887&directionsmode=driving',
  },
  {
    id: 4,
    color: '#ff7043',
    name: 'Alabasterküste',
    region: 'Criel-sur-Mer · Normandie',
    dates: '25.–30. Mai',
    km: '500',
    dauer: '6 Std.',
    naechte: 5,
    start: new Date('2026-05-25'),
    end:   new Date('2026-05-30'),
    unterkunft: "Horizon d'Opale",
    adresse: '2 Impasse des Cygnes, 76910 Criel-sur-Mer',
    checkin: '25. Mai · Schlüsselbox',
    checkout: '30. Mai',
    buchungNr: null,
    buchungUrl: 'https://www.airbnb.de/trips/v1/reservation-details/ro/RESERVATION2_CHECKIN/HMXXPYRX39',
    buchungPlattform: 'Airbnb',
    info: 'Direkt am Strand. 180° Meerblick, 3. OG. Parkplatz B33. ⭐ 4.88 — ⚠️ Klippen-Abbruchgefahr.',
    lat: 50.0197, lng: 1.3098,
    navUrl: 'https://maps.google.com/maps?daddr=50.0197,1.3098&directionsmode=driving',
  },
];

const KATEGORIEN = ['RESTAURANTS', 'WANDERN / AUSFLÜGE', 'BESONDERHEITEN', 'SUPERMARKT', 'UNTERKUNFT'];
